routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
  if(Auth::guest())
    return view('auth.login');                   
  else
    return view('home');

});

Route::get('/remisiones', function () {
  return view('home_remisiones');
});


Auth::routes();

Route::get('/logout', function () {
  Auth::logout();
  return redirect('/');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/role', 'RoleController')->names('role');


Route::resource('/parametros', 'ParametrosRemisionController')->names('parametros');
Route::resource('/conferencias', 'ConferenciasController')->names('conferencias');
Route::resource('/regionales', 'RegionalesController')->names('regionales');

Route::resource('/categorias/conferencias', 'CategoriasConferenciasController')->names('categoriasconferencias');



Route::get('/categorias/conferencias/keyup/{valor?}', 'CategoriasConferenciasController@keyup');
Route::get('/regionales/keyup/{valor?}', 'RegionalesController@keyup');

Route::get('/reportes/completo', 'ReportesController@completo')->name('reportes.completo');

Route::post('/reportes/generar/completo', 'ReportesController@generar');
Route::post('/reportes/exportar/pdf', 'ReportesController@exportarPDF');
Route::post('/reportes/exportar/csv', 'ReportesController@exportarCSV');



Route::resource('/user', 'UserController', ['except' => [
        'create', 'store']])->names('user');

app/Http/Controllers/ConferenciasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class ConferenciasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $conferencias = DB::table('tabla_detalle_categoria_conferencia')
                        ->select('tabla_detalle_categoria_conferencia.*', 'tabla_conferencias.*', 'tabla_categoria_conferencia.*')
                        ->join('tabla_conferencias', 'tabla_detalle_categoria_conferencia.id_conferencia_fk', '=', 'tabla_conferencias.id_conferencia')
                        ->join('tabla_categoria_conferencia', 'tabla_detalle_categoria_conferencia.id_categoria_fk', '=', 'tabla_categoria_conferencia.id_categoria')->paginate(10);

        return view('conferencias.index', compact('conferencias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $categorias_conferencias = DB::table('tabla_categoria_conferencia')->where('estado_categoria', 1)->get();

        return view('conferencias.crear', compact('categorias_conferencias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   

        $request->validate([
            'categoria' => 'required',
            'descripcion_conferencia' => 'required',
            'estado_conferencia' => 'required'
        ]);

        DB::table('tabla_conferencias')->insert([
            'descripcion_conferencia' => $request->descripcion_conferencia,
            'estado_conferencia' => $request->estado_conferencia
        ]);

         $conferencias = DB::table('tabla_conferencias')->where('estado_conferencia', 1)->orderby('id_conferencia','DESC')->take(1)->get();

         foreach ($conferencias as $conferencia) {
            DB::table('tabla_detalle_categoria_conferencia')->insert([
                'id_conferencia_fk' => $conferencia->id_conferencia,
                'id_categoria_fk' => $request->categoria
            ]);
         };

         return redirect()->route('conferencias.index')->with('status_success','Registro exitoso!'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $categorias_conferencias = DB::table('tabla_categoria_conferencia')->where('estado_categoria', 1)->get();

        $conferencias = DB::table('tabla_detalle_categoria_conferencia')
                        ->select('tabla_detalle_categoria_conferencia.*', 'tabla_conferencias.*', 'tabla_categoria_conferencia.*')
                        ->join('tabla_conferencias', 'tabla_detalle_categoria_conferencia.id_conferencia_fk', '=', 'tabla_conferencias.id_conferencia')
                        ->join('tabla_categoria_conferencia', 'tabla_detalle_categoria_conferencia.id_categoria_fk', '=', 'tabla_categoria_conferencia.id_categoria')
                        ->where('tabla_conferencias.id_conferencia', $id)->get();
    
        return view('conferencias.edicion', compact('conferencias', 'categorias_conferencias')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'categoria' => 'required',
            'descripcion_conferencia' => 'required',
            'estado_conferencia' => 'required'
        ]);

        DB::table('tabla_conferencias')->where('id_conferencia', $id)->update([
            'descripcion_conferencia' => $request->descripcion_conferencia,
            'estado_conferencia' => $request->estado_conferencia
        ]);

        DB::table('tabla_detalle_categoria_conferencia')->where('id_conferencia_fk', $id)->update([
            'id_categoria_fk' => $request->categoria
        ]);

        
        return redirect()->route('conferencias.index')->with('status_success','Actualizacion exitosa!'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        DB::table('tabla_conferencias')->where('id_conferencia', $id)->update([
            'estado_conferencia' => 0
        ]);

        return redirect()->route('conferencias.index')->with('status_success','Borrado exitoso!'); 
    }
}

resources/views/conferencias/crear.blade.php
@extends('layouts.app')

@section('content')
<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Crear conferencia</h3>
                </div>

                <div class="card-body">
                    <div class="alert alert-danger">
                        <b>TODOS</b> los campos marcados con asteriscos (*) son obligatorios.
                    </div>
                    @include('custom.message')
                    <form action="{{ route('conferencias.store') }}" method="POST">
                        @csrf
                        @method('POST')


                        <div class="form-group">
                            <div class="row">
                                <div class="col">
                                    <label style="padding-bottom: 3px;"><b>(*) Categoria conferencia:</b></label>

                                    <select class="form-control mi-selector" name="categoria" required="">
                                        <option value="">Seleccionar regional</option>
                                        @foreach($categorias_conferencias as $categoria)
                                            <option value="{{ $categoria->id_categoria }}">{{ $categoria->descripcion_categoria }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col">
                                    <label style="padding-bottom: 3px;"><b>(*) Nombre conferencia:</b></label>
                                    <input type="text" class="form-control" name="descripcion_conferencia" placeholder="Nombre categoria" required="">
                                </div>
                                <div class="col">
                                    <label style="padding-bottom: 3px;"><b>(*) Estado conferencia:</b></label>
                                    <select class="form-control" name="estado_conferencia" required="">
                                        <option value="1">Activo</option>
                                        <option value="0">Inactivo</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="botones col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12" style="margin-top: 40px; margin-bottom: 20px;">
                            <center>
                                <a href="{{ route('conferencias.index') }}">
                                <button class="btn btn-danger" type="button">
                                    <i class="fas fa-ban"></i> Cancelar conferencia
                                </button>
                                </a>
                                <button class="btn btn-success" type="submit">
                                    <i class="fas fa-paper-plane"></i> Registrar conferencia
                                </button>
                            </center>
                        </div>
                    </form>
                </div>

              </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/conferencias/edicion.blade.php
@foreach($conferencias as $conferencia)
<div class="container">
	 @include('custom.parameters')
	  {!! Form::open(['route' => array('conferencias.update', $conferencia->id_conferencia), 'files' => true]) !!}
	  	
		@csrf
		@method('PUT')

		<div class="form-group">
			<div class="row">
				<div class="col">
					<label style="padding-bottom: 3px;"><b>(*) Categoria conferencia:</b></label>
					<select class="form-control mi-selector" name="categoria" required="">
						<option value="">Seleccionar regional</option>
						@foreach($categorias_conferencias as $categoria)
							@if($categoria->id_categoria == $conferencia->id_categoria)
								<option value="{{ $categoria->id_categoria }}" selected="">{{ $categoria->descripcion_categoria }}</option>
							@else
								<option value="{{ $categoria->id_categoria }}">{{ $categoria->descripcion_categoria }}</option>
							@endif
						@endforeach
					</select>
				</div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<div class="col">
					<label style="padding-bottom: 3px;"><b>(*) Nombre conferencia:</b></label>
					<input type="text" class="form-control" name="descripcion_conferencia" placeholder="Nombre categoria" required="" value="{{ $conferencia->descripcion_conferencia }}">
				</div>
				<div class="col">
					<label style="padding-bottom: 3px;"><b>(*) Estado conferencia:</b></label>
					<select class="form-control mi-selector" name="estado_conferencia" required="">
						@if($conferencia->estado_conferencia == '1')
							<option value="1" selected="">Activo</option>
							<option value="0">Inactivo</option>
						@else
							<option value="1" >Activo</option>
							<option value="0" selected="">Inactivo</option>
						@endif

					</select>
				</div>
			</div>
		</div>

		<div class="botones col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12" style="margin-top: 40px; margin-bottom: 20px;">
			<center>
				<button class="btn btn-danger" type="button" data-dismiss="modal">
					<i class="fas fa-ban"></i> Cancelar conferencia
				</button>
				</a>
				<button class="btn btn-success" type="submit">
					<i class="fas fa-sync-alt"></i> Actualizar conferencia
				</button>
			</center>
		</div>
	{!! Form::close() !!}
</div>
<script type="text/javascript">
	    $(document).ready(function () {
        $('.mi-selector').select2();
        $('.mi-selector-tabla').select2();
        $('.mi-selector-tabla-producto').select2();

    });

</script>
@endforeach

resources/views/conferencias/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content" >
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Listado de las conferencias</h3>
                </div>

                <div class="card-body">
                    @include('custom.message')
                    <div class="table-responsive">
	                    <div class="form-group">
	                        <label><b>Búsqueda de una conferencia...</b></label>
	                        <input type="text" class="form-control" id="busqueda_conferencia" name="busqueda_conferencia" placeholder="Digite descripcion conferencia">
	                    </div>
	                    <table class="table table-hover table-bordered" id="resultado_consulta">
	                    	<thead>
	                    		<tr>
	                    			<th scope="col">ID</th>
	                    			<th scope="col">Nombre conferencia</th>
	                    			<th scope="col">Categoria conferencia</th>
	                    			<th scope="col">Estado conferencia</th>
	                    			<th colspan="3"><center>Acciones</center></th>
	                    		</tr>
	                    	</thead>
	                    	<tbody>
	                    		@foreach($conferencias as $conferencia)
	                    			<tr>
	                    				<td>{{ $conferencia->id_conferencia }}</td>
	                    				<td>{{ $conferencia->descripcion_conferencia }}</td>
	                    				<td>{{ $conferencia->descripcion_categoria }}</td>
	                    				@if($conferencia->estado_conferencia == '1')
		                                    <td class="alert alert-success">Activo</td>
		                                @else
		                                    <td class="alert alert-danger">Inactivo</td>
		                                @endif
		                                <td style="text-align: center;">
		                                    <button type="button" class="btn btn-success btnEdicion" title="Editar registro" data-id="{{ $conferencia->id_conferencia }}" data-url="{{ route('conferencias.edit', $conferencia->id_conferencia ) }}"><i class="far fa-edit"></i></button>
		                                </td>
		                                <td>
		                                    <center>
		                                    <form method="POST" action="{{ route('conferencias.destroy', $conferencia->id_conferencia)}}">
		                                        @csrf
		                                        @method('DELETE')
		                                        <button type="submit" class="btn btn-danger" title="Eliminar registro">
		                                            <i class="fas fa-calendar-minus"></i>
		                                        </button>
		                                    </form>
		                                    </center>
		                                </td>
	                    			</tr>
	                    		@endforeach                    		
	                    	</tbody>
	                    </table>
	                    {{ $conferencias->links() }}
                	</div>
                </div>

              </div>
            </div>
        </div>
    </div>
</div>


@endsection