routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
  if(Auth::guest())
    return view('auth.login');                   
  else
    return view('home');

});

Route::get('/remisiones', function () {
  return view('home_remisiones');
});


Auth::routes();

Route::get('/logout', function () {
  Auth::logout();
  return redirect('/');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/role', 'RoleController')->names('role');


Route::resource('/parametros', 'ParametrosRemisionController')->names('parametros');
Route::resource('/conferencias', 'ConferenciasController')->names('conferencias');
Route::resource('/regionales', 'RegionalesController')->names('regionales');

Route::resource('/categorias/conferencias', 'CategoriasConferenciasController')->names('categoriasconferencias');



Route::get('/categorias/conferencias/keyup/{valor?}', 'CategoriasConferenciasController@keyup');
Route::get('/regionales/keyup/{valor?}', 'RegionalesController@keyup');

Route::get('/reportes/completo', 'ReportesController@completo')->name('reportes.completo');

Route::post('/reportes/generar/completo', 'ReportesController@generar');
Route::post('/reportes/exportar/pdf', 'ReportesController@exportarPDF');
Route::post('/reportes/exportar/csv', 'ReportesController@exportarCSV');



Route::resource('/user', 'UserController', ['except' => [
        'create', 'store']])->names('user');

app/Http/Controllers/RegionalesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class RegionalesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $regionales = DB::table('tabla_regionales')->paginate(10);

        return view('regionales.index', compact('regionales'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('regionales.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'descripcion_regional' => 'required',
            'estado_regional' => 'required'
        ]);

        DB::table('tabla_regionales')->insert([
            'descripcion_regional' => $request->descripcion_regional,
            'estado_regional' => $request->estado_regional
        ]);

        return redirect()->route('regionales.index')->with('status_success','Registro exitoso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $regionales = DB::table('tabla_regionales')->where('id_regional', $id)->get();

        return view('regionales.edicion', compact('regionales'));
    }

    public function keyup($data){
        
        $regionales = DB::table('tabla_regionales')
                    ->where("descripcion_regional", 'like', $data . "%")->get();

        return view('regionales.keyup', compact('regionales'));

    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'descripcion_regional' => 'required',
            'estado_regional' => 'required'
        ]);

        DB::table('tabla_regionales')->where('id_regional', $id)->update([
            'descripcion_regional' => $request->descripcion_regional,
            'estado_regional' => $request->estado_regional
        ]);

        return redirect()->route('regionales.index')->with('status_success','Registro exitoso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('tabla_regionales')->where('id_regional', $id)->update([
            'estado_regional' => '0',
        ]);

        return redirect()->route('regionales.index')
            ->with('status_success','Borrado exitoso!');
    }
}

resources/views/regionales/crear.blade.php
@extends('layouts.app')

@section('content')
<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Crear regionales</h3>
                </div>

                <div class="card-body">
                	<div class="alert alert-danger">
                		<b>TODOS</b> los campos marcados con asteriscos (*) son obligatorios.
                	</div>
                    
                    @include('custom.message')

                    <form action="{{ route('regionales.store') }}" method="POST">
                    	@csrf
                    	@method('POST')

                    	<div class="form-group">
                    		<div class="row">
                    			<div class="col">
                    				<label style="padding-bottom: 3px;"><b>(*) Nombre regional: </b></label>
                    				<input type="text" class="form-control" name="descripcion_regional" placeholder="Nombre regional" required="">
                    			</div>
                    			<div class="col">
                    				<label style="padding-bottom: 3px;"><b>(*) Estado regional: </b></label>
                    				<select class="form-control" name="estado_regional">
                    					<option value="1">Activo</option>
                    					<option value="0">Inactivo</option>
                    				</select>
                    			</div>
                    		</div>
                    	</div>

                    	<div class="botones col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12" style="margin-top: 40px; margin-bottom: 20px;">
                            <center>
                            	<a href="{{ route('regionales.index') }}">
                                <button class="btn btn-danger" type="button">
                                    <i class="fas fa-ban"></i> Cancelar registro
                                </button>
                            	</a>
                                <button class="btn btn-success" type="submit">
                                    <i class="fas fa-paper-plane"></i> Registrar regional
                                </button>
                            </center>
                        </div>
                    </form>
                </div>

              </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/regionales/edicion.blade.php
@foreach($regionales as $regional)
<div class="container">
	 @include('custom.parameters')
	 
	 {!! Form::open(['route' => array('regionales.update', $regional->id_regional), 'files' => true]) !!}

		@csrf
		@method('PUT')
	
		<div class="form-group">
			<div class="row">
				<div class="col">
					<label style="padding-bottom: 3px;"><b>(*) Nombre regional:</b></label>
					<input type="text" class="form-control" name="descripcion_regional" placeholder="Nombre regional" required="" value="{{ $regional->descripcion_regional }}">
				</div>
				<div class="col">
					<label style="padding-bottom: 3px;"><b>(*) Estado regional:</b></label>
					<select class="form-control" name="estado_regional">
						@if($regional->estado_regional == '1')
							<option value="1" selected="">Activo</option>
							<option value="0">Inactivo</option>
						@else
							<option value="1">Activo</option>
							<option value="0" selected="">Inactivo</option>
						@endif
					</select>
				</div>
			</div>
		</div>
		

		<div class="botones col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12" style="margin-top: 40px; margin-bottom: 20px;">
			<center>
				<button class="btn btn-danger" type="button" data-dismiss="modal" aria-label="Close">
					<i class="fas fa-ban"></i> Cancelar actualizacion
				</button>
				<button class="btn btn-success" type="submit">
					<i class="fas fa-sync-alt"></i> Actualizar
				</button>
			</center>
		</div>

	{!! Form::close() !!}
</div>
@endforeach

resources/views/regionales/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content" >
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Listar regionales</h3>
                </div>

                <div class="card-body">
                    @include('custom.message')
                    <div class="table-responsive">
	                    <div class="form-group">
	                        <label><b>Búsqueda de una regional...</b></label>
	                        <input type="text" class="form-control" id="busqueda_regional" name="busqueda_regional" placeholder="Digite descripcion regional">
	                    </div>
	                    <table class="table table-hover table-bordered" id="resultado_consulta">
	                    	<thead>
	                    		<tr>
	                    			<th scope="col">ID</th>
	                    			<th scope="col">Nombre regional</th>
	                    			<th scope="col">Estado regional</th>
	                    			<th colspan="3"><center>Acciones</center></th>
	                    		</tr>
	                    	</thead>
	                    	<tbody>
	                    		@foreach($regionales as $regional)
	                    			<tr>
	                    				<td>{{ $regional->id_regional }}</td>
	                    				<td>{{ $regional->descripcion_regional }}</td>
	                    				@if($regional->estado_regional == '1')
		                                    <td class="alert alert-success">Activo</td>
		                                @else
		                                    <td class="alert alert-danger">Inactivo</td>
		                                @endif
		                                <td style="text-align: center;">
		                                    <button type="button" class="btn btn-success btnEdicion" title="Editar registro" data-id="{{ $regional->id_regional }}" data-url="{{ route('regionales.edit', $regional->id_regional ) }}"><i class="far fa-edit"></i></button>
		                                </td>
		                                <td>
		                                    <center>
		                                    <form method="POST" action="{{ route('regionales.destroy', $regional->id_regional)}}">
		                                        @csrf
		                                        @method('DELETE')
		                                        <button type="submit" class="btn btn-danger" title="Eliminar registro">
		                                            <i class="fas fa-calendar-minus"></i>
		                                        </button>
		                                    </form>
		                                    </center>
		                                </td>
	                    			</tr>
	                    		@endforeach                    		
	                    	</tbody>
	                    </table>
	                    {{ $regionales->links() }}
                	</div>
                </div>

              </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/regionales/keyup.blade.php
<thead>
	                    		<tr>
	                    			<th scope="col">ID</th>
	                    			<th scope="col">Nombre regional</th>
	                    			<th scope="col">Estado regional</th>
	                    			<th colspan="3"><center>Acciones</center></th>
	                    		</tr>
	                    	</thead>
	                    	<tbody>
	                    		@foreach($regionales as $regional)
	                    			<tr>
	                    				<td>{{ $regional->id_regional }}</td>
	                    				<td>{{ $regional->descripcion_regional }}</td>
	                    				@if($regional->estado_regional == '1')
		                                    <td class="alert alert-success">Activo</td>
		                                @else
		                                    <td class="alert alert-danger">Inactivo</td>
		                                @endif
		                                <td style="text-align: center;">
		                                    <button type="button" class="btn btn-success btnEdicion" title="Editar registro" data-id="{{ $regional->id_regional }}" data-url="{{ route('regionales.edit', $regional->id_regional ) }}"><i class="far fa-edit"></i></button>
		                                </td>
		                                <td>
		                                    <center>
		                                    <form method="POST" action="{{ route('regionales.destroy', $regional->id_regional)}}">
		                                        @csrf
		                                        @method('DELETE')
		                                        <button type="submit" class="btn btn-danger" title="Eliminar registro">
		                                            <i class="fas fa-calendar-minus"></i>
		                                        </button>
		                                    </form>
		                                    </center>
		                                </td>
	                    			</tr>
	                    		@endforeach                    		
	                    	</tbody>